### ISSUE TITLE
No confirmation page

### ISSUE THREAD

**Issue by ScotteSolutionsLtd** [GBSEcom/paymentJS_php_integration#1]
In reviewing the code, it appears there is no way to present the buyer with a confirmation screen. 

When a buyer enters their payment information, is there no supported way of capturing the input so to present a confirmation page where they can review the order before proceeding/processing? This example does processing upon submission of the credit card form fields that are injected via iframe. It doesn't seem to support entering payment information on one page and confirming on the next page - like my website has been doing for roughly 12 years.

Can this example be adapted/altered to capture payment information in one step and process the payment in another step?

**Comment by jslingerland** [comment]
Hi there,

no, that would defeat the purpose of what payment.js provides from a PCI compliance standpoint. As soon as the form is submitted, the credit card data is sent directly from the consumer's browser to First Data/Fiserv for processing, and a token is returned. The card data bypasses your server entirely (which is different than how yours works today, for good reason). Typically in a shopping cart scenario such as yours when using a product like payment.js, the tokenization request would be sent from the payment page, and then the subsequent authorization would be sent once the order is actually confirmed.
The other alternative to this is having the payment form *and* the order confirmation on the same page, where when the form is submitted, it will tokenize the credit card and then perform the authorization in one step as two separate callouts.

**Comment by ScotteSolutionsLtd** [comment]
Hi and thanks for your reply on the issue. I do have a follow up question:

When the data in the form bypasses the server during tokenization as you described, the server is left unable to create a properly formed **transaction request** because those values (name, card number, expiry, cvv) are required parameters to later create the transaction. If name, card number, expiry and CVV bypass the server, they can't be saved or used to later build a request to process the actual transaction, post-successful tokenization.

When I look at the docs and testing here https://developer.payeezy.com/apis, if any of those 4 fields are not available or sent with the subsequent transaction request, the API will return an error saying the field is required. 

I don't see an API example that doesn't require those 4 fields as parameters so I'm not sure what's missing. Any help would be much appreciated!
